[directory]
format = "[in](#7f745b) [$path](#82c0af) "

[character]
success_symbol = "[#](blue)"
error_symbol	=  "[#](red)"

[username]
format = "ğŸ™ ğŸ’® [$user](#d4c787) "
disabled = false
show_always = true

[git_branch]
format = '[on](#7f745b) [$symbol$branch(:$remote_branch)]($style) '

[git_status]
format = '$all_status$ahead_behind '
staged = "ğŸš…"
modified = "ğŸš€"
deleted = "âŒ"
renamed = "ğŸ"
conflicted = "ğŸ‘¹"
untracked = "ğŸ£"


