[directory]
format = "[on](red) $path "

[character]
success_symbol = "[#](blue)"

[username]
format = "ğŸ™ [$user]($style) in "
style_user = 'green bold'
style_root = 'black bold'
disabled = false
show_always = true

[git_status]
format = '$all_status$ahead_behind '
modified = "ğŸ”´"
staged = "ğŸš„"
up_to_date = "Hello"
