[directory]
format = "[on](red) $path "

[character]
success_symbol = "[#](blue)"

[username]
format = "ğŸ™ ğŸ’® [$user]($style) "
style_user = 'green bold'
style_root = 'black bold'
disabled = false
show_always = true

[git_status]
format = '$all_status$ahead_behind '
staged = "ğŸš…"
modified = "ğŸš€"
deleted = "âŒ"
renamed = "ğŸ"
conflicted = "ğŸ‘¹"
untracked = "ğŸ£"
